### PR TITLE
fix : https://wso2.org/jira/browse/ML-65

### PR DESCRIPTION
**Pull request by manoramahp**
Added input validation to check whether the feature values are empty.

### CODE REVIEW

**Comment by nirmal070125** [comment]
Are we showing an error if the values are empty?

**Comment by manoramahp** [comment]
Yes. Error shown is "Feature value is required." under each empty input field.

**Comment by manoramahp** [comment]
Yes. The error shown is "Feature value is required" under each empty input
field.

On Fri, Jun 5, 2015 at 9:36 AM, Nirmal Fernando <notifications@github.com>
wrote:

> Are we showing an error if the values are empty?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wso2/product-ml/pull/161#issuecomment-109156520>.
>



-- 
Manorama Perera
Software Engineer
WSO2, Inc.;  http://wso2.com/
Mobile : +94716436216

**Comment by nirmal070125** [comment]
Great ! thanks.

**Pull request merged**
